"""Local-only source port and verified Tier 1 adapters."""

from survey_scribe.sources.base import (
    DEFAULT_SOURCE_LIMITS,
    LocalSource,
    ResolvedSource,
    SourceAdapter,
    SourceBlock,
    SourceBundle,
    SourceConversionError,
    SourceCoverage,
    SourceDependencyError,
    SourceDiagnostic,
    SourceDocument,
    SourceError,
    SourceFormatError,
    SourceInputError,
    SourceLimitError,
    SourceLimits,
    SourceProvenance,
    SourceSecurityError,
    SourceTable,
    SourceTimeoutError,
    resolve_local_source,
    snapshot_resolved_source,
)
from survey_scribe.sources.registry import SourceRegistry

__all__ = [
    "DEFAULT_SOURCE_LIMITS",
    "LocalSource",
    "ResolvedSource",
    "SourceAdapter",
    "SourceBlock",
    "SourceBundle",
    "SourceConversionError",
    "SourceCoverage",
    "SourceDependencyError",
    "SourceDiagnostic",
    "SourceDocument",
    "SourceError",
    "SourceFormatError",
    "SourceInputError",
    "SourceLimitError",
    "SourceLimits",
    "SourceProvenance",
    "SourceRegistry",
    "SourceSecurityError",
    "SourceTable",
    "SourceTimeoutError",
    "resolve_local_source",
    "snapshot_resolved_source",
]
