"""Public package surface for Survey Scribe."""

from importlib.metadata import version

from survey_scribe.client import SurveyScribe
from survey_scribe.config import SurveyScribeConfig
from survey_scribe.errors import (
    AmbiguousCredentialError,
    ArtifactCollisionError,
    ArtifactWriteError,
    ClientClosedError,
    ConfigurationError,
    ConversionFailedError,
    ProgrammerInputError,
    RunningEventLoopError,
    SurveyScribeError,
)
from survey_scribe.models import (
    AnswerCategory,
    CandidateEdge,
    CandidateStatus,
    Containment,
    DataType,
    DiagnosticSeverity,
    DiscrepancyKind,
    EdgeKind,
    EvidenceRecord,
    InventoryItem,
    LoopDefinition,
    LoopKind,
    NumericRange,
    QuestionnaireRoutingGraph,
    RepeatKind,
    RepeatSpec,
    ReplacementEdge,
    ReviewAction,
    ReviewDecision,
    RoutedAnswerCategory,
    RoutedNumericRange,
    RoutedSurveySVIS,
    RoutedSurveyVariable,
    RoutingAudit,
    RoutingDiagnostic,
    RoutingDiscrepancy,
    RoutingEdge,
    RoutingNode,
    RoutingSourceBinding,
    StudyType,
    SurveySVIS,
    SurveyVariable,
    TerminalKind,
    UnitLevel,
    canonical_routing_schema_json,
)
from survey_scribe.pipeline import ChunkedStructuredPipeline, StructuredPipeline
from survey_scribe.results import (
    Diagnostic,
    DiagnosticCode,
    ExtractionResult,
    FailedBlock,
    ResultStatus,
)
from survey_scribe.routing import QuestionnaireRouter, RoutingConfig
from survey_scribe.sources import (
    LocalSource,
    SourceBundle,
    SourceConversionError,
    SourceDependencyError,
    SourceError,
    SourceFormatError,
    SourceInputError,
    SourceLimitError,
    SourceSecurityError,
    SourceTimeoutError,
)

__all__ = [
    "AnswerCategory",
    "AmbiguousCredentialError",
    "ArtifactCollisionError",
    "ArtifactWriteError",
    "CandidateEdge",
    "CandidateStatus",
    "ChunkedStructuredPipeline",
    "ClientClosedError",
    "ConfigurationError",
    "Containment",
    "ConversionFailedError",
    "DataType",
    "Diagnostic",
    "DiagnosticCode",
    "DiagnosticSeverity",
    "DiscrepancyKind",
    "EdgeKind",
    "EvidenceRecord",
    "ExtractionResult",
    "FailedBlock",
    "InventoryItem",
    "LoopDefinition",
    "LoopKind",
    "LocalSource",
    "NumericRange",
    "QuestionnaireRouter",
    "QuestionnaireRoutingGraph",
    "ProgrammerInputError",
    "RepeatKind",
    "RepeatSpec",
    "ReplacementEdge",
    "ReviewAction",
    "ReviewDecision",
    "ResultStatus",
    "RoutedAnswerCategory",
    "RoutedNumericRange",
    "RoutedSurveySVIS",
    "RoutedSurveyVariable",
    "RoutingAudit",
    "RoutingConfig",
    "RoutingDiagnostic",
    "RoutingDiscrepancy",
    "RoutingEdge",
    "RoutingNode",
    "RoutingSourceBinding",
    "RunningEventLoopError",
    "SourceBundle",
    "SourceConversionError",
    "SourceDependencyError",
    "SourceError",
    "SourceFormatError",
    "SourceInputError",
    "SourceLimitError",
    "SourceSecurityError",
    "SourceTimeoutError",
    "StructuredPipeline",
    "StudyType",
    "SurveySVIS",
    "SurveyScribe",
    "SurveyScribeConfig",
    "SurveyScribeError",
    "SurveyVariable",
    "TerminalKind",
    "UnitLevel",
    "__version__",
    "canonical_routing_schema_json",
]

__version__ = version("survey-scribe")
