"""
Foundry coded-agent entrypoint for Blob-backed survey extraction.

Flow:
1. Accept a file name (not a full path)
2. Download input/<file_name> from Azure Blob Storage
3. Run the existing Docling extraction pipeline locally
4. Upload output JSON to output/<file_stem>_result.json

Authentication uses DefaultAzureCredential so a system-assigned managed
identity can be used in Foundry runtime.
"""
from __future__ import annotations

import argparse
import tempfile
from pathlib import Path

from azure.identity import DefaultAzureCredential
from azure.storage.blob import BlobServiceClient, ContentSettings

from docling_pipeline import run

STORAGE_ACCOUNT_NAME = "gmdaiharmonizationdemo"
STORAGE_CONTAINER_NAME = "survey-scribe"
INPUT_PREFIX = "input"
OUTPUT_PREFIX = "output"


def _require_file_name(file_name: str) -> None:
    if not file_name:
        raise ValueError("file_name is required")
    if "/" in file_name or "\\" in file_name:
        raise ValueError("file_name must be only a file name, not a path")


def _blob_paths(file_name: str) -> tuple[str, str]:
    input_blob = f"{INPUT_PREFIX}/{file_name}"
    output_blob = f"{OUTPUT_PREFIX}/{Path(file_name).stem}_result.json"
    return input_blob, output_blob


def run_from_blob(file_name: str) -> dict:
    """Run the full extraction pipeline for one file from Blob Storage."""
    _require_file_name(file_name)

    credential = DefaultAzureCredential()
    account_url = f"https://{STORAGE_ACCOUNT_NAME}.blob.core.windows.net"
    blob_service = BlobServiceClient(account_url=account_url, credential=credential)
    container = blob_service.get_container_client(STORAGE_CONTAINER_NAME)

    input_blob_name, output_blob_name = _blob_paths(file_name)

    with tempfile.TemporaryDirectory(prefix="survey_scribe_") as temp_dir:
        temp_root = Path(temp_dir)
        local_input = temp_root / file_name
        local_output_dir = temp_root / "output"

        # Download source PDF from Blob.
        download_stream = container.download_blob(input_blob_name)
        local_input.write_bytes(download_stream.readall())

        output_file = run(local_input, local_output_dir)
        if output_file is None or not output_file.exists():
            return {
                "status": "skipped",
                "input_blob": input_blob_name,
                "output_blob": output_blob_name,
                "message": "No output generated by pipeline (scanned/invalid/empty conversion).",
            }

        output_bytes = output_file.read_bytes()
        output_blob = container.get_blob_client(output_blob_name)
        output_blob.upload_blob(
            output_bytes,
            overwrite=True,
            content_settings=ContentSettings(content_type="application/json"),
        )

    return {
        "status": "success",
        "input_blob": input_blob_name,
        "output_blob": output_blob_name,
        "bytes_uploaded": len(output_bytes),
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run survey extraction by downloading input file from Azure Blob Storage.",
    )
    parser.add_argument("file_name", help="Input file name under input/ in Blob container")
    args = parser.parse_args()

    result = run_from_blob(args.file_name)
    print(result)


if __name__ == "__main__":
    main()
