name: Publish to PyPI

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    environment: pypi

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.8.11"
          enable-cache: true

      - run: uv sync --locked --all-extras --python 3.11

      - run: uv build

      - run: uv run --no-sync twine check --strict dist/*.whl dist/*.tar.gz

      - run: uv publish --trusted-publishing always dist/*.whl dist/*.tar.gz
